### ISSUE TITLE
lost agent session

### ISSUE THREAD

**Issue by AlexLisong** [dstpierre/lcsk#11]
Hello,
I successfully installed it on my asp.net webform website.
After I logged in as an agent and then click agent panel link, or if I close the browser tab, the session got lost, and I couldn't log in as the same agent.
However from the front end visitor page, the visitor still see the chat window, he can still send message to that agent, but there is no way to see the message from the back end(the agent page)
Any help will be appreciated.
Thanks,

**Comment by farshid3003** [comment]
Now there is another problem.
If I login with an agent and close explorer and open and login again I cannot receive any message and I cannot see old messages. It means I miss my session or get new connection ID without mapping to old Connection ID

**Comment by farshid3003** [comment]
in AgentConnect method you should change it like this :

// if the agent is already signed-in
                if (Agents.Any(x => x.Key == name))
                {
//Change Old Chats
                    if (ChatSessions.Any(c => c.Value == Agents[name].Id))
                    {
                        var chatSessionId = ChatSessions.First(c => c.Value == Agents[name].Id).Key;
                        ChatSessions[chatSessionId] = Context.ConnectionId;
                    }
//Assign new connection ID to old agent
                    Agents[name].Id = Context.ConnectionId;
                    agent = Agents[name];

                    Clients.Caller.loginResult(true, agent.Id, agent.Name);

                    Clients.All.onlineStatus(Agents.Count(x => x.Value.IsOnline) > 0);
                }

after connect to old session in js you shold open old chat screen 
or if agent leave page you should send close chat too all visitors

**Comment by salmanshariati** [comment]
would you please tell me when this bug will be fixed?

**Comment by efficiondave** [comment]
We had this same issue and it makes it unusable. Chat's get totally lost in the void and in very limited testing we find it happens even without closing tabs and browsers. Seems like there needs to be some kind of regular polling to verify the agent client is still responding and if not, log them out.

**Comment by johnfcporto** [comment]
how to do that efficiondave?

**Comment by efficiondave** [comment]
Don't know. I gave up on LCSK and went with a commercial product.

**Comment by chrismaliszewski** [comment]
efficiondave - we're having same issue. I consider spending some time on it to (let's hope) resolve that issue but...

Can you tell me what commercial product you chose finially in your case?
