### ISSUE TITLE
after login it does not show user name in message

### ISSUE THREAD

**Issue by farshid3003** [dstpierre/lcsk#15]
If user loged it it should get user name from User.Identity and show username in chat.

**Comment by dstpierre** [comment]
LCSK uses its own username, not all ASP.NET sites uses the built-it identity manager. Plus, the LCSK is all about HTML, they are not Views / Pages. Simply plain old HTML pages.

**Comment by farshid3003** [comment]
I mean Customer not agent :) 
As you said agent has own user name but each application has own identity management you can force application to give you Customer Username to show the name on chat view.
is it clear ?
