### ISSUE TITLE
Cannot Login Or Create DAT file

### ISSUE THREAD

**Issue by msachais** [dstpierre/lcsk#21]
I am running VS 2013, Framework 4.5, I have demo installed on same computer and that works fine.  I added LCSK into my WebForms project using Nuget.  Changed the Startup.CS Demo.LCSK.Startup to my namespace so everything compiles. The chat shows up in bottom right of my site and I can email from it (after configuring the sendmail script) when I run my project.

I added an empty App_Dat folder to the project.  I run my project and go to /lcsk/install.html and only the admin login shows up (which is different than the demo which shows both the agent and admin password).  When I type a password and hit button, nothing happens.  When I go to agent.html and enter password and click button nothing happens.  I then copied lcsk.dat from demo project into my project app_data directory, run project and go to agent.html to try to log in and still nothing happens when I click button.  Any idea what may be issue.  Thank you for your help.

**Comment by dstpierre** [comment]
> only the admin login shows up

You should delete the App_Data/lcsk.dat file before requesting the install.html page. If there's a lcsk.dat file you see the login instead.

Couple of things to try/check out:

1) Make sure you click (with mouse) on those button, the Enter key / form submit is not well handled, specifically in the agent.html page.

2) Make sure you have write access to the App_Data folder

3) Now that the lcsk.dat file is deleted go to the install.html page and set the two passwords.

4) if you still cannot save put a breakpoint on line 391 of the LCSK/ChatHub.cs file which will break with you click on the Save Changes of the install.html page.

Hope that helps

**Comment by msachais** [comment]
I found issue... this line of code:

string configPath = HttpContext.Current.Server.MapPath("~/App_Data/" + CONFIG_FILE);

has a null HttpContext when it executes which just causes the processing to stop and appear like nothing happens when you click the button. Is there any special setup on the project to be able to access the pages.  I am currently accessing by http://localhost:1350/lcsk/install.html

**Comment by msachais** [comment]
I fixed issue by making following code change:

string configPath = Path.Combine(HttpRuntime.AppDomainAppPath, "App_Data/" + CONFIG_FILE);

Thank you.
