### ISSUE TITLE
Integration in a class Library and web app

### ISSUE THREAD

**Issue by johnfcporto** [dstpierre/lcsk#23]
I have a class library with my chatHub.cs and then i have my web aplication with html files and so on.
Is it possible to integration your code in the class library and making it work?

I tried to copy all the methdos in your chatHub.cs to my chathub.cs then I copied LCSK folder to my web app.

I removed agent.cs from that folder and put it on my class library in models folder.

When i run the application and make install.html the start page.. I type a password, then i click login and i got a bunch of errors:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) 
http://localhost:51858/signalr/hubs

Uncaught TypeError: Cannot read property 'client' of undefined
2install.js:13 Uncaught TypeError: Cannot read property 'server' of undefined

**Comment by dstpierre** [comment]
Seems like you're missing the `app.MapSignalR();` from the startup.cs file. Your hub does not appears to be registered.

**Comment by johnfcporto** [comment]
using System;
using System.Threading.Tasks;
using Microsoft.Owin;
using Owin;

[assembly: OwinStartup(typeof(WebLiveSupport.Startup))]

namespace WebLiveSupport
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.MapSignalR();
        }
    }
}

i got this in my startup file. Still getting this error 
Uncaught TypeError: Cannot read property 'client' of undefined

**Comment by dstpierre** [comment]
the link to the signalr javascript is not working or your version of jQuery / SignalR are not matching. Make sure you use the version included in the LCSK folder first.

**Comment by johnfcporto** [comment]
the problem is:

if I have the chathub.cs in lcsk folder it works well, but if I comment all the lines of chathub.cs. And then i copy this file to my class library(only chathub.cs). it stops working.

Consider I've added reference of the class library(dll) to my web application.

I get this error on this line in chat.js gets undefined: var myHub = $.connection.chatHub;

**Comment by johnfcporto** [comment]
I fix it. I forgot i add to install Microsoft ASP.NET SignalR package in the webapplication too.. the next step is to to have agent.cs in class library too..

**Comment by johnfcporto** [comment]
in this scenario the webapp is much slower than having all in the web application!! do you know why dstpierre?

**Comment by bilalizloo** [comment]
Can you share some code, i am facing the same situation, i have the signal r packages on both sides class library and web application.  i have explain my scenario here 

http://stackoverflow.com/questions/40232297/how-can-i-create-a-hub-object-in-n-layer-architecture
