### ISSUE TITLE
Saving conversations in sql Database

### ISSUE THREAD

**Issue by johnfcporto** [dstpierre/lcsk#26]
How can I save messages in sql database?

Can you explain it to me?

Thanks

**Comment by qgate** [comment]
I have same question

**Comment by dstpierre** [comment]
LCSK uses the in-memory SignalR mechanism, SignalR handle message saving in all sorts of database, You might want to add this package https://www.nuget.org/packages/Microsoft.AspNet.SignalR.SqlServer/2.2.0 with proper configuration and SignalR will use a database instead.

Here's a tutorial that could help: http://www.asp.net/signalr/overview/performance/scaleout-with-sql-server

Good luck.
