### ISSUE TITLE
Agent different login system

### ISSUE THREAD

**Issue by johnfcporto** [dstpierre/lcsk#31]
I want to implement an agent login system where i have a sql database with a table called users, with a column bool IsAdmin.

My idea is when I go to ...LCSK/Agent.html i put some credentials, then it goes to db and login or not depending if it's and admin or not.. can you help me?

**Comment by jhermiz** [comment]
lcsk currently does not support server side logs, everything is stored in html5 storage sessions.  If you want to approach the agent route against a database you will have to look into adding sql server support via rsignal / sql server features.
