### ISSUE TITLE
"Engage In Chat" should open the message window

### ISSUE THREAD

**Issue by jhermiz** [dstpierre/lcsk#33]
If I'm an agent and I see via the agent.html file that a new user has entered my site.  If I click "Engage User" it should open up the messaging window on the user's side, otherwise all they hear is a beep.  They then have to click this message window to actually see that I am trying to interact with them.

How would an end user ever know you are interacting with them if this window remains shut ?

@dstpierre you've got this for EngageVisitor

        public void EngageVisitor(string connectionId)
        {
            var agent = _agents.SingleOrDefault(x => x.Value.Id == Context.ConnectionId).Value;
            if (agent == null) return;
            _chatSessions.TryAdd(connectionId, agent.Id);
            Clients.Caller.newChat(connectionId);
            Clients.Client(connectionId).setChat(connectionId, agent.Name, false);
            Clients.Caller.addMessage(connectionId, "system", "You invited this visitor to chat...");
            Clients.Client(connectionId).addMessage(agent.Name, "Hey there. I'm " + agent.Name + " let me know if you have any questions.");
        }

Is there a way to somehow call: $("#chat-box").slideToggle(); immediately after this call so that the visitor knows someone is interacting with them?

**Comment by jhermiz** [comment]
Hmm, this doesn't do what I would expect, it still is just producing a beep.  Shouldn't it open the chat window on the clients machine ?

**Comment by jhermiz** [comment]
@dstpierre inside of `agent.js` you need to add the following:

        `$("#chat-box").slideToggle();`

This is within the `myHub.client.newChat` function.  I can fork the current, branch it, make the changes and do a pull request if you don't mind.

**Comment by jhermiz** [comment]
I went ahead and submitted a pull request.  This is now officially working.  When an agent "initates" a chat with the client, the client's chat window will auto open automatically.  This is a nice feature so now the client knows someone is talking to them.

**Comment by dstpierre** [comment]
The sound is played only from the agent point of view. To test this, open the agent.html and from another browser open the demo website.

From the agent Engage the other browser to chat, the chat box should open on the other browser.

**Comment by jhermiz** [comment]
But it doesn't I tried it.  But if you merge my pull request this works.  Check my pull request.  Open two browser windows, one as an agent, the second as a user.  As an agent "Initiate" or "Engage" the client to a chat with my changes.  Look at the other client browser window, you will see the chat window open up automatically.

Now try it out without the pull request, (current master of lcsk), you will see this does not happen.  Tested on chrome, and IE 12.

**Comment by dstpierre** [comment]
I just tried, I implemented this morning :). Make sure you did a refresh on your browser playing the role of the visitor. I've added a JavaScript function this morning that do open the chat for visitor when engaged.

The agent.js file is not loaded for visitor, that cannot make the chat box for visitor appears.

**Comment by jhermiz** [comment]
For me, with all cache, history, and downloads cleared and everything wiped out it doesnt work for me.  But If I run my pull request code, it works.  I don't know what to tell you, I cannot blame it on cache as all cache is deleted.  Can you just for testing purposes, run my pull request and see if it works for you?

**Comment by jhermiz** [comment]
Strange now I removed all cookies, cache, etc and rebooted, and commented my code and now all is well.

Please delete my pull request!
