### ISSUE TITLE
Error on Aspx page

### ISSUE THREAD

**Issue by johnfcporto** [dstpierre/lcsk#38]
Copied the 3 lines to my aspx login page.

    <script src="Modules/LiveSupport/lcsk/assets/js/jquery.signalR-2.1.1.min.js" type="text/javascript"></script>
    <script src="/signalr/hubs" type="text/javascript" type="text/javascript"></script>
    <script src="Modules/LiveSupport/lcsk/chat.js" type="text/javascript"></script>

The other one, jquery reference was already there
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>

And when I'm running the app I get this errors:

![image](https://cloud.githubusercontent.com/assets/3793129/8429213/7aecb754-1f1d-11e5-8718-68bc06902306.png)

Can you help?

**Comment by jhermiz** [comment]
I've had this issue in the past and once I cleared my cache / history this disappeared.
