### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by johnfcporto** [dstpierre/lcsk#40]
How can i be a contributor?
I want to add some funcionalities i've been developping

**Comment by jhermiz** [comment]
lcsk is open source, you need to fork it on github, clone it, create a branch make a feature / bug fix, merge it into your master forked version and then push it back to your forked version on github.  Once you've done that you need to do a pull request on github.  Not everything is merged into the master lcsk trunk, only features / bug fixes which are accepted by the community.

**Comment by jhermiz** [comment]
@johnfcporto Can this issue please be closed as this is not a valid issue for lcsk, this is about github.
