### ISSUE TITLE
For a visitor same chatId

### ISSUE THREAD

**Issue by alicankablan** [dstpierre/lcsk#64]
Hi,

I have a old project I use ASP.NET 4.5 Webform.I have some problems I didnt change  anyting in code and try it  many times. The visitor on the webpage cant get only one( 1 ) chatId because of this I see him always as a different visitor when he change page.

**Try :**
I change sessionStorage to localStorage but it doesnt work. 

Any solution?

**Comment by dstpierre** [comment]
I'm sorry there's no support for LCSK, I am changing the project to a new chat (and way more). I don't have access to Windows anymore so I cannot try to reproduce your issue, the only thing I can help with for now is:

a) make sure you have the latest version, clone the `lcsk` branch
b) The code of LCSK was released a long time ago if you are not using the same version of some dependencies that could introduce some bug maybe.

The good news is that I'm starting active development on the new solution.

Good luck.
